apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
{{- range $service, $val := .Values.services }}
{{- range $labelKey, $labelVal := $val.labels }}
{{- if eq $labelKey "helm.docker-compose.tlsSecret" }}
  tls:
  - secretName: {{ $labelVal }}
{{- end}}
{{- end}}
{{- end}}
  backend:
    serviceName: {{ .Release.Name }}
    servicePort: 80