apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
{{- range $service, $val := .Values.services }}
{{- range $labelKey, $labelVal := $val.labels }}
{{- if eq $labelKey "helm.docker-compose.tlsSecret" }}
  tls:
  - secretName: {{ $labelVal }}
{{- end }}
{{- end }}
{{- end }}
  rules:
  - host: "{{ `{{ .Values.SERVER_NAME }}` }}"
    http:
      paths:
      {{- range $service, $val := .Values.services }}
      {{- range $labelKey, $labelVal := $val.labels }}
      {{- if eq $labelKey "helm.docker-compose.ingress.port" }}
      - backend:
          serviceName: {{ $service }}
          servicePort: {{ $labelVal }}
        {{- range $labelKey2, $labelVal2 := $val.labels }}
        {{- if eq $labelKey2 "helm.docker-compose.ingress.prefix" }}
        path: "{{ $labelVal2 }}"
        {{- end }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
