{{ range $service, $val := .Values.services }}
---
# Source!: signature-commons/templates/service-{{ $service }}.yaml
apiVersion: v1
kind: Service
metadata:
  name: "{{ $service }}"
spec:
  type: NodePort
  ports:
  {{- range $k, $v := $val.ports }}
  - name: "{{ splitList ":" $v | first }}"
    port: {{ splitList ":" $v | first }}
    targetPort: {{ splitList ":" $v | last }}
  {{- end }}
  selector:
    workload.user.cattle.io/workloadselector: "deployment-{{ $service }}"
{{ end }}
