version: "3"

services:
  # Front-end to entire framework proxy API connections
  #  and potentially handle load balancing in the future.
  proxy:
    build:
      context: packages/proxy
    image: maayanlab/proxy:1.1.7
    labels:
      kompose.image-pull-policy: "Always"
      kompose.service.expose: "true"
    restart: "on-failure"
    networks:
      default:
      internal:
        aliases:
          - proxy
    environment:
      nginx_server_name: "${SERVER_NAME}"
      nginx_proxy_00: "${META_API_PREFIX}(/.*) http://metadata-api:3000${META_API_PREFIX}$$1"
      nginx_proxy_01: "${DATA_API_PREFIX}(/.*) http://data-api:8080${DATA_API_PREFIX}$$1"
      nginx_proxy_02: "${UI_PREFIX}(/.*) http://ui:80${UI_PREFIX}$$1"
      nginx_buffering: "0"
    ports:
      - 80:80
      # - 443:443

# Internal docker networks
networks:
  internal:
