version: '3'

services:
  # Front-end to entire framework proxy API connections
  #  and potentially handle load balancing in the future.
  proxy:
    build: ./proxy
    image: maayanlab/signature-commons-proxy
    networks:
      default:
      internal:
        aliases:
          - proxy
    environment:
      nginx_server_name: localhost
      nginx_proxy_00: "/sigcom-dev/ http://ui:80/sigcom-dev/"
      nginx_proxy_03: "/signature-commons-metadata-api/ http://metadata-api:3000/signature-commons-metadata-api/"
      nginx_proxy_04: "/enrichmentapi/ http://data-api:8080/enrichmentapi/"
      nginx_redirect_00: "/sigcom/ /sigcom-dev/"
    ports:
      - 80:80
      # - 443:443

  # UI rendering, facilitates integration of metadata and data apis
  ui:
    image: maayanlab/sigcom-dev
    networks:
      internal:
        aliases:
          - ui

  # Metadata API, facilitates json-validatable
  #  database interactions with metadata postgresql DB
  metadata-api:
    image: maayanlab/signature-commons-metadata-api
    networks:
      internal:
        aliases:
          - metadata-api
    env_file: .env
    # environment:
    #   DEBUG: "*"
    #   ADMIN_PASSWORD: youruser
    #   ADMIN_USERNAME: yourpass
    #   TYPEORM_CONNECTION=postgres
    #   TYPEORM_URL=postgresql://yourdbuser:yourdbpass@metadata-db:5432/signaturestore
    #   TYPEORM_ENTITIES=dist/src/entities/*.js
    #   TYPEORM_MIGRATIONS=dist/src/migration/*.js
    #   TYPEORM_SUBSCRIBERS=dist/src/subscriber/*.js

  # Data API, facilitates efficient data-level analysis
  data-api:
    image: maayanlab/enrichmentapi
    networks:
      internal:
        aliases:
          - data-api
    env_file: .env
    environment:
      deployment: marathon_deployed
      # token: yourtoken
      # AWS_ACCESS_KEY_ID: yourawsaccesskey
      # AWS_SECRET_ACCESS_KEY: yourawssecret
      # aws_bucket: yourbucket

  # NOTE: If databases are stored elsewhere, they just need to be
  #  configured via the environment variables and commented out in this file.
  # Metadata database, underlying store of metadata
  metadata-db:
    build: ./metadata-db
    image: maayanlab/metadata-db
    networks:
      internal:
        aliases:
          - metadata-db
    env_file: .env
    # environment:
    #   POSTGRES_PASSWORD: signaturestore
    #   POSTGRES_USER: signaturestore
    volumes:
      - metadata-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

# Internal volumes
volumes:
  metadata-db:

# Internal docker networks
networks:
  internal:
