# Source: signature-commons/templates/deployment.yaml
# Source!: signature-commons/templates/deployment-ui.yaml
{{ if ne .Values.UI "false" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-ui
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-ui
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-ui
    spec:
      containers:
      - name: ui
        image: maayanlab/sigcom:latest
        imagePullPolicy: Always
        env:
        - name: NEXT_PUBLIC_DATA_API
          value: "{{ .Values.DATA_API_PREFIX }}"
        - name: NEXT_PUBLIC_ENRICHR_URL
          value: "{{ .Values.ENRICHR_API_PREFIX }}"
        - name: NEXT_PUBLIC_METADATA_API
          value: "{{ .Values.META_API_PREFIX }}"
        - name: PREFIX
          value: "{{ .Values.UI_PREFIX }}"
        ports:
          - containerPort: 80
{{ end }}
