# Source: signature-commons/templates/service.yaml
# Source!: signature-commons/templates/service-ui.yaml
{{ if ne .Values.UI false }}
apiVersion: v1
kind: Service
metadata:
  name: "ui"
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: "deployment-ui"
{{ end }}
