# Source: signature-commons/templates/service.yaml
# Source!: signature-commons/templates/service-data-api.yaml
{{ if ne .Values.DATA_API "false" }}
apiVersion: v1
kind: Service
metadata:
  name: "data-api"
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: "deployment-data-api"
{{ end }}
