# Source: docker-compose/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: signature-commons
  labels:
    app: signature-commons
spec:
  type: NodePort
  ports:
  selector:
    app: signature-commons

apiVersion: v1
kind: Service
metadata:
  name: signature-commons
  labels:
    app: signature-commons
spec:
  type: NodePort
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  selector:
    app: signature-commons

apiVersion: v1
kind: Service
metadata:
  name: signature-commons
  labels:
    app: signature-commons
spec:
  type: NodePort
  ports:
  selector:
    app: signature-commons

apiVersion: v1
kind: Service
metadata:
  name: signature-commons
  labels:
    app: signature-commons
spec:
  type: NodePort
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app: signature-commons

apiVersion: v1
kind: Service
metadata:
  name: signature-commons
  labels:
    app: signature-commons
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: signature-commons

apiVersion: v1
kind: Service
metadata:
  name: signature-commons
  labels:
    app: signature-commons
spec:
  type: NodePort
  ports:
  selector:
    app: signature-commons
