{{ range $service, $val := .Values.services }}
{{- range $labelKeyPort, $labelValPort := $val.labels }}
{{- if eq $labelKeyPort "helm.docker-compose.ingress.port" }}
{{- range $labelKeyPrefix, $labelValPrefix := $val.labels }}
{{- if eq $labelKeyPrefix "helm.docker-compose.ingress.prefix" }}
---
# Source!: signature-commons/templates/ingress-{{ $service }}.yaml
{{- range $labelKeyActive, $labelValActive := $val.labels }}
{{- if eq $labelKeyActive "helm.docker-compose.toggle-active" }}
{{`#!{{ if ne .Values.`}}{{ $labelValActive }}{{` false }}`}}
{{- end }}
{{- end }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-{{ $service }}
spec:
  rules:
  - host: "{{ `{{ .Values.SERVER_NAME }}` }}"
    http:
      paths:
      - backend:
          serviceName: {{ $service }}
          servicePort: {{ $labelValPort }}
        path: "{{ $labelValPrefix }}"
{{- range $labelKeyActive, $labelValActive := $val.labels }}
{{- if eq $labelKeyActive "helm.docker-compose.toggle-active" }}
{{ `#!{{ end }}` }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{ end }}