{{ range $service, $val := .Values.services }}
---
# Source!: signature-commons/templates/service-{{ $service }}.yaml
{{- range $labelKeyActive, $labelValActive := $val.labels }}
{{- if eq $labelKeyActive "helm.docker-compose.toggle-active" }}
{{`#!{{ if ne .Values.`}}{{ $labelValActive }}{{` "false" }}`}}
{{- end }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ $service }}"
spec:
  type: NodePort
  ports:
  {{- range $k, $v := $val.ports }}
  - name: "{{ splitList ":" $v | first }}"
    port: {{ splitList ":" $v | first }}
    targetPort: {{ splitList ":" $v | last }}
  {{- end }}
  selector:
    workload.user.cattle.io/workloadselector: "deployment-{{ $service }}"
{{- range $labelKeyActive, $labelValActive := $val.labels }}
{{- if eq $labelKeyActive "helm.docker-compose.toggle-active" }}
{{ `#!{{ end }}` }}
{{- end }}
{{- end }}
{{ end }}
